name: test
on:
  pull_request:
  push:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app

jobs:
  test:
    uses: trinhngocthuyen/gh-actions/.github/workflows/rb-test.yml@main
